#!/bin/bash
# Build a custom container on top of standard kas container.
# 
# We use this container for a variety of tasks in our build system.
set -e
. $ROOT_DIR/.env
_VERBOSITY=1
#verbose && hdr "Entered $0"
cd "$ROOT_DIR"
(set -x; docker login ghcr.io)
if ! (
    set -x; 
    docker buildx build \
    --build-arg SOURCE_DATE_EPOCH="$(git log -1 --pretty=%ct)" \
    --output type=docker,rewrite-timestamp=true \
    --progress=plain \
    --tag "$KAS_CONTAINER_IMAGE" \
    --file "$ROOT_DIR"/kas.Dockerfile .
) then
    echo "Build failed!"
    return 1
fi
#verbose && hdr "Exiting $0"
